config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
    resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 3 }
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Renvoie le condensé de hachage de la chaîne donnée
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Combinaison email / mot de passe invalide'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
        @user = User.new(user_params)    # Not the final implementation!
      if @user.save
        log_in @user
        flash[:success] = "Bienvenue dans la Sample App!"
        redirect_to @user
      else
        render 'new'
      end
      puts params
    end

    def show
      if logged_in?
        @user = User.find(params[:id])
      else
        redirect_to login_path
      end
    end

    def index
      if logged_in?
      else
      redirect_to login_path
      end
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private

      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Enregistrements dans l'utilisateur donné
  def log_in(user)
    session[:user_id] = user.id
  end

  #  Se souvient d'un utilisateur dans une session persistante.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Renvoie l'utilisateur connecté actuel (le cas échéant).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Retourne true si l'utilisateur est connecté, sinon false.
  def logged_in?
    !current_user.nil?
  end

  # Oublie une session persistante
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Déconnecte l'utilisateur courant
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
<div class="col-sm-3 sidenav">
  <h4>Super Club</h4>
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><%= link_to "Accueil", root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Page du club", users_path %></li>
      <li><%= link_to "Se déconnecter", logout_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Se connecter", login_path %></li>
      <li><%= link_to "S'inscrire", '/users/new'%></li>
    <% end %>
  </ul><br>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Club</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">

    <%= render 'layouts/header' %>

    <div class="col-sm-9">
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>

    </div>
  </div>
</div>

<%= debug(params) if Rails.env.development? %>

<footer class="container-fluid">
  <p>Footer Text</p>
</footer>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>

  <% if logged_in? %>
    <li><%= link_to "Page du club", users_path %></li>
  <% else %>
  <h3> Connecte-toi pour accéder à la page du club </h3>
    <li><%= link_to "Se connecter", login_path %></li>
    <li><%= link_to "S'inscrire", '/users/new'%></li>
  <% end %>
</div>

app/views/users/index.html.erb
<h4><small>UTILISATEURS</small></h4>
<% User.all.each do |element| %>
<hr>
<h2><%= element.first_name %>
    <%= element.last_name %>
</h2>
<h5><span class="glyphicon glyphicon-time"></span> Post at <%= element.created_at %></h5>
<h5><span class="label label-danger"><%= element.email %></span></h5><br>
<p>Food is my passion. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<br><br>
<% end %>

<h4>Leave a Comment:</h4>
<form role="form">
  <div class="form-group">
    <textarea class="form-control" rows="3" required></textarea>
  </div>
  <button type="submit" class="btn btn-success">Submit</button>
</form>
<br><br>

<p><span class="badge">2</span> Comments:</p><br>

<div class="row">
  <div class="col-sm-2 text-center">
    <img src="bandmember.jpg" class="img-circle" height="65" width="65" alt="Avatar">
  </div>
  <div class="col-sm-10">
    <h4>Anja <small>Sep 29, 2015, 9:12 PM</small></h4>
    <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <br>
  </div>
  <div class="col-sm-2 text-center">
    <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
  </div>
  <div class="col-sm-10">
    <h4>John Row <small>Sep 25, 2015, 8:25 PM</small></h4>
    <p>I am so happy for you man! Finally. I am looking forward to read about your trendy life. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <br>
    <p><span class="badge">1</span> Comment:</p><br>
    <div class="row">
      <div class="col-sm-2 text-center">
        <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
      </div>
      <div class="col-xs-10">
        <h4>Nested Bro <small>Sep 25, 2015, 8:28 PM</small></h4>
        <p>Me too! WOW!</p>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Inscription</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :first_name, "Prénom" %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name, "Nom" %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password, "Mot de passe" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.email %>